# fly.toml app configuration file generated for rd-data-import on 2025-02-11T13:11:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rd-data-import'
primary_region = 'lhr'

[build]

[[mounts]]
source = 'data'
destination = '/data'

[http_service]
internal_port = 3000
force_https = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2
