name: Lint JS
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-importer:
    defaults:
      run:
        working-directory: ./lib/importer
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm i
    - name: Run linter
      run: npm run lint
