name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    defaults:
      run:
        working-directory: ./prototypes/basic
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install lib dependencies -- todo, check why
      working-directory: ./lib/importer
      run: npm i
    - name: Install dependencies
      run: npm i
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: ./prototypes/basic/test-results
        retention-days: 30
  importer:
    defaults:
      run:
        working-directory: ./lib/importer
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install lib dependencies
      run: npm i
    - name: Run tests
      run: npm run test
